exp: adversarial # only valid for "synthetic", "cutest", "adversarial", "fine-tuning"
device: cpu # only valid for "cuda", "cpu", "mps"

# experiment options
model: cnn
dataset: mnist # only valid for "mnist", "cifar10"
idx: 1 # -1 for random choice
x_dim: 784 # attack tensor dimension, make sure be equal to image size
seed: 456
num_iterations: 2000
optimizers: # multiple optimizers for fair comparison, valid for "fo", "zo", "rl", "rl_w_hoistory", "relizo"
  - fo
  - zo
  - rl
  - rl_w_history
  - relizo

# optimization options
lr: 0.01
betas: # momentum for first / second moment
  - 0.9
  - 0.99
epsilon: 1.0e-8 # epsilon

# ---- # for ZO algorithm
num_queries: 10 # number of query samples
variance: 0.1 # variance

# ---- # for RL RL w/ hiatory algorithm
num_histories: 15 # number of histories