exp: adversarial
device: cuda

# Adversarial Attack: CIFAR-10 (TODO.md)
model: cnn
dataset: cifar10
idx: 1
seed: 456
x_dim: 3072  # 32x32x3
num_iterations: 3000

optimizers:
  - vanilla
  - zoar
  - relizo
  - twopoint
  - zohs
  - sepcmaes
  - adasmooth_es

# optimization options
lr: 0.01
betas: [0.9, 0.99]
epsilon: 1.0e-8
update_rule: radazo

# ZO algorithm
num_queries: 10
mu: 0.05
num_histories: 5
population_size: 10

# AdaSmoothES best configuration
adaptive_beta: cma_match
cma_decay: 0.001
baseline: mean
