exp: adversarial # only valid for "synthetic", "cutest", "adversarial", "fine-tuning"
device: cpu # only valid for "cuda", "cpu", "mps"

# experiment options
model: cnn
dataset: mnist # only valid for "mnist", "cifar10"
idx: 1 # image index
seed: 456
x_dim: 784 # attack tensor dimension, make sure be equal to image size
num_iterations: 20000
optimizers: # multiple optimizers for fair comparison, valid for "fo", "zo", "rl", "rl_w_hoistory", "relizo", "zohs", "zohs_expavg"
  # - fo
  - vanilla # Vallina
  # - rl # 
  - zoar_0 # ZoAR without history
  - zoar # ZoAR
  - relizo # ReLIZO
  - zohs # ZOHS
  # - zohs_expavg

# optimization options
lr: 0.01
betas: # momentum for first / second moment
  - 0.9
  - 0.99
epsilon: 1.0e-8 # epsilon
update_rule: radazo # "sgd", "adam", "radazo"

# ---- # for ZO algorithm
num_queries: 2 # number of query samples
mu: 0.5 # zo eps

# ---- # for RL RL w/ hiatory algorithm
num_histories: 5 # number of histories